export const authTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  REGISTER_USER: "REGISTER_USER",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  REFRESH_INFO: "REFRESH_INFO",
};

export const messageTypes = {
  ADD_USER: "ADD_USER",
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  GET_MESSAGES: "GET_MESSAGES",
  UPDATED_GET_MESSAGES: "UPDATED_GET_MESSAGES",
  GET_CONVERSATIONS: "GET_CONVERSATIONS",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  CHECK_ONLINE_OFFLINE: "CHECK_ONLINE_OFFLINE",
};

export const notifyTypes = {
  REMOVE_NOTIFY: "REMOVE_NOTIFY",
  CREATE_NOTIFY: "CREATE_NOTIFY",
  GET_NOTIFIS: "GET_NOTIFIS",
  UPDATE_NOTIFy: "UPDATE_NOTIFy",
  DELETE_ALL_NOTIFies: "DELETE_ALL_NOTIFies",
  UPDATE_SOUND: "UPDATE_SOUND",
};

export const alertTypes = {
  ALERT_MESSAGE: "ALERT_MESSAGE",
};

export const themeType = {
  THEME: "THEME",
};
export const statusType = {
  STATUS: "STATUS",
};

export const modalTypes = {
  MODAL: "MODAL",
};

export const discoverTypes = {
  DISCOVER_LOADING: "DISCOVER_LOADING",
  GET_DISCOVER_POSTS: "GET_DISCOVER_POSTS",
  UPDATE_DISCOVER_POSTS: "UPDATE_DISCOVER_POSTS",
};

export const profileTypes = {
  SEARCH_PROFILES: "SEARCH_PROFILES",
  GET_PROFILE: "GET_USER_PROFILE",
  GET_ID: "GET_PROFILE_ID",
  GET_USERS: "GET_USER",
  LOADING: "LOADING_PROFILE",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  GET_USER_POSTS: "GET_USER_POSTS",
  UPDATE_PROFILE_POST: "UPDATE_PROFILE_POST",
};

export const postTypes = {
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
  EDITE_POST: "EDITE_POST",
  GET_POST: "GET_POST",
  GET_POSTS: "GET_POSTS",
  LOADING_POST: "LOADING_POST",
};

export const commentTypes = {
  CREATE_COMMENT: "CREATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  EDITE_COMMENT: "EDITE_COMMENT",
  GET_COMMENT: "GET_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  LOADING_COMMENT: "LOADING_COMMENT",
};

export const seggestionsTypes = {
  LOADING_SUGGESTIONS: "LOADING_SUGGESTIONS",
  GET_USERS_SUGGESTIONS: "GET_USERS_SUGGESTIONS",
};

export const globalTypes = {
  SOCKET: "SOCKET",
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  CALL: "CALL",
  PEER: "PEER",
};
